'use strict';

/**
 * F3 acceptance (integration, REAL OpenVoice V2 model + real onnxruntime):
 * the brief's chunking pin, measured rather than argued —
 *
 *   "a >30 s input produces the same output as an unchunked run of the same
 *    audio, to a stated tolerance, and RSS stays bounded."
 *
 * The 70 s fixture (`test-assets/long70.wav`, regenerated by its generator
 * when absent) is decimated 2:1 to the model's fixed 22050 Hz — an EXACT
 * integer ratio out of 44100, so input preparation introduces no resampler of
 * its own into a measurement about chunking. 70 s at 22050 Hz is 1,543,500
 * samples, which the plan splits into THREE chunks with two seams; anything
 * shorter than 659,712 samples (~29.9 s) would be a single chunk and could
 * not measure chunking at all, so the fixture length is load-bearing and is
 * asserted below.
 *
 * Inference runs in a CHILD process (`scripts/voice-bench-driver.cjs`) — the
 * same one-process-per-run shape as the app's utilityProcess arrangement, and
 * required anyway because onnxruntime's tensor type checks need same-realm
 * Float32Arrays, which Jest's vm sandbox cannot provide. That driver exposes
 * two modes over the SAME module primitives:
 *
 *   'host'   — the shipped path: createVoiceHost's message loop, chunked.
 *   'direct' — one converter run over the whole utterance, fed the SAME
 *              source tone (the host's own per-chunk mean) so the comparison
 *              isolates the CHUNKING and nothing else.
 *
 * This file owns gating, input preparation and every assertion; it recomputes
 * each comparison from the two written f32 files with its own arithmetic
 * rather than trusting a number the driver reports.
 *
 * ---------------------------------------------------------------------------
 * THE STATED TOLERANCE — and why it is not "sample-identical everywhere"
 * ---------------------------------------------------------------------------
 * The exported decoder is deterministic but NOT frame-shift-equivariant:
 * extending the analysis window to the left by a SINGLE hop decorrelates the
 * interior completely (rms|diff| 0.349 against a signal rms of 0.186 — the
 * difference is larger than the signal; measured, and recorded in
 * voiceChunking.cjs's header). A chunk that starts mid-file therefore renders
 * the same words in the same voice with entirely different fine structure.
 * Demanding sample identity past the first seam would be demanding something
 * this model does not offer, and a test that demanded it could only ever be
 * satisfied by not chunking at all. So the tolerance is stated in three
 * parts, each matched to what is actually claimable:
 *
 *   1. PREFIX — chunk 0 shares the unchunked run's start, so it is the one
 *      place with a phase-locked ground truth. Two assertions, because they
 *      say different things:
 *        (a) BIT-IDENTICAL (exactly zero) up to the first crossfade MINUS the
 *            discard margin — ~28.5 s;
 *        (b) below 1e-4 all the way UP TO the crossfade. This is the one that
 *            sizes the margin, and it is sharply discriminating: measured
 *            2.05e-7 with the shipped 64-frame margin against 3.37e-1 with
 *            the 2-frame margin the first draft used — a factor of 1.6
 *            million. Chunk 0 starts drifting 26,259 samples before its end
 *            (26,265 under the pre-fix plan; the source tone is a mean over
 *            the plan's own chunks, so the onset moves a few samples with the
 *            geometry), and the margin's whole job is to keep the crossfade
 *            out of that drift while it is still ~130 dB down.
 *   2. ENVELOPE — the 20 ms RMS envelopes correlate >= 0.95 and total RMS
 *      agrees within 1.0 dB. This is a coarse "the two runs are the same
 *      audio" check and NOT a seam check: it measures 0.975-0.978 under every
 *      arrangement tried, including the broken 2-frame margin, so it cannot
 *      tell a good seam from a bad one and does not claim to.
 *   3. SEAM CONTINUITY — the crossfade window's own RMS against the
 *      equal-length windows either side of it, bounded at 3.5 dB (measured
 *      +2.08 dB). This deliberately does NOT compare against the unchunked
 *      run: that comparison was tried, and away from any seam it already
 *      spreads +/-14.26 dB purely from rendition decorrelation, so every
 *      bound below 14 dB was measuring noise rather than the join. What this
 *      does catch is a join that drops the signal (-inf) or double-adds it
 *      (+4.6 dB at the measured correlation). It does not discriminate
 *      constant power from equal gain at this crossfade length, and says so
 *      rather than claiming a rejected design would fail it.
 *
 * RSS boundedness is asserted as the property that matters: the chunked run's
 * peak stays BELOW the unchunked run's on the same input, and doubling the
 * input length does not double it (the unchunked path's own measured law is
 * linear, ~183 MB + 5.4 MB per second).
 *
 * ---------------------------------------------------------------------------
 * GATING — a plain `npm test` never downloads 160 MB
 * ---------------------------------------------------------------------------
 * The bench runs only when the pinned model set is already in the repo-local
 * cache (`test-assets/models/voice/`, gitignored), and otherwise REPORTS a
 * skip (`test.skip`, reason in the name — never a silent green).
 * `VOICE_INTEGRATION=1` makes a missing set a FAILURE rather than a skip: you
 * asked for the full path, so not having it is a real failure. Same policy as
 * stemIntegration.test.cjs and transcribeIntegration.test.cjs.
 */

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync, spawnSync } = require('node:child_process');

const { VOICE_FILES, VOICE_MODEL_DIR } = require('./voiceManager.cjs');
const {
  VC_SAMPLE_RATE,
  SEGMENT_SAMPLES,
  EDGE_DISCARD_SAMPLES,
  CROSSFADE_SAMPLES,
  planVoiceSegments,
  crossfadeStart,
} = require('./voiceChunking.cjs');

jest.setTimeout(20 * 60 * 1000);

const REPO = path.resolve(__dirname, '..');
const MODEL_DIR = path.join(REPO, 'test-assets', VOICE_MODEL_DIR);
const OUT_DIR = path.join(REPO, 'test-output');
const DRIVER = path.join(REPO, 'scripts', 'voice-bench-driver.cjs');
const LONG70 = path.join(REPO, 'test-assets', 'long70.wav');
const MAKE_LONG = path.join(REPO, 'scripts', 'make-test-long.cjs');

const optIn = process.env.VOICE_INTEGRATION === '1';

/** Collection-time gate: presence + exact size for EVERY pinned file. The
 * sha256 pins are the manager's job and are verified there before any load;
 * this is only "is the set here at all". */
const modelPaths = Object.fromEntries(
  VOICE_FILES.map((f) => [f.key, path.join(MODEL_DIR, f.filename)])
);
const modelsOnDisk = VOICE_FILES.every((f) => {
  try {
    return fs.statSync(modelPaths[f.key]).size === f.bytes;
  } catch {
    return false;
  }
});
const benchTest = modelsOnDisk || optIn ? test : test.skip;

function requireModels() {
  if (!modelsOnDisk) {
    throw new Error(
      `the pinned voice model set is not in ${MODEL_DIR} — download it in-app ` +
        `(Pipeline -> Voice Changer -> Download Models) and copy it there, or unset ` +
        `VOICE_INTEGRATION to let this test skip`
    );
  }
}

/** Writes a raw little-endian Float32 mono buffer for the driver. */
function writeF32(name, samples) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const out = path.join(OUT_DIR, name);
  const buf = Buffer.alloc(samples.length * 4);
  for (let i = 0; i < samples.length; i++) buf.writeFloatLE(samples[i], i * 4);
  fs.writeFileSync(out, buf);
  return out;
}

function readF32(file) {
  const raw = fs.readFileSync(file);
  const out = new Float32Array(raw.length / 4);
  for (let i = 0; i < out.length; i++) out[i] = raw.readFloatLE(i * 4);
  return out;
}

/**
 * The 70 s fixture, decimated 2:1 from 44100 Hz to the model's 22050 Hz. The
 * ratio is exact, so this is a pure sample selection — no interpolation, no
 * filter, nothing that could be mistaken for the chunking's doing. (The
 * fixture is a slow sweep plus deterministic LCG noise, not speech: this test
 * measures the SPLICE, and identity movement was settled by the spike against
 * real voices with an independent verifier.)
 */
function prepareSource() {
  if (!fs.existsSync(LONG70)) {
    execFileSync(process.execPath, [MAKE_LONG], { stdio: 'ignore' });
  }
  const b = fs.readFileSync(LONG70);
  if (b.toString('ascii', 0, 4) !== 'RIFF' || b.toString('ascii', 8, 12) !== 'WAVE') {
    throw new Error(`${LONG70} is not a RIFF/WAVE file`);
  }
  const channels = b.readUInt16LE(22);
  const rate = b.readUInt32LE(24);
  const bits = b.readUInt16LE(34);
  if (rate !== 2 * VC_SAMPLE_RATE || channels !== 1 || bits !== 16) {
    throw new Error(`${LONG70} must be mono 16-bit ${2 * VC_SAMPLE_RATE} Hz (got ${channels}ch ${bits}-bit ${rate} Hz)`);
  }
  const frames = (b.length - 44) / 2;
  const out = new Float32Array(Math.floor(frames / 2));
  for (let i = 0; i < out.length; i++) out[i] = b.readInt16LE(44 + i * 2 * 2) / 32768;
  return out;
}

/** Runs the driver once and returns its JSON verdict plus the output audio. */
function runDriver(mode, sourcePath, referencePath, tag) {
  const job = {
    paths: { extractor: modelPaths.extractor, converter: modelPaths.converter },
    mode,
    source: sourcePath,
    reference: referencePath,
    outAudio: path.join(OUT_DIR, `voice-bench-${tag}.f32`),
    out: path.join(OUT_DIR, `voice-bench-${tag}.json`),
  };
  const jobPath = path.join(OUT_DIR, `voice-bench-${tag}-job.json`);
  fs.writeFileSync(jobPath, JSON.stringify(job));
  const run = spawnSync(process.execPath, [DRIVER, jobPath], {
    encoding: 'utf8',
    timeout: 15 * 60 * 1000,
    maxBuffer: 16 * 1024 * 1024,
  });
  expect(run.error).toBeUndefined();
  if (!fs.existsSync(job.out)) {
    throw new Error(`driver produced no verdict; stdout=${run.stdout}\nstderr=${run.stderr}`);
  }
  const verdict = JSON.parse(fs.readFileSync(job.out, 'utf8'));
  if (!verdict.ok) throw new Error(`driver (${mode}) failed: ${verdict.error}\nstderr=${run.stderr}`);
  expect(run.status).toBe(0);
  return { verdict, audio: readF32(job.outAudio) };
}

/** 20 ms RMS frames — the same grid the spike used for envelope correlation. */
const FRAME = Math.round(0.02 * VC_SAMPLE_RATE); // 441 samples
function rmsFrames(x) {
  const n = Math.floor(x.length / FRAME);
  const out = new Float64Array(n);
  for (let f = 0; f < n; f++) {
    let s = 0;
    for (let i = f * FRAME; i < (f + 1) * FRAME; i++) s += x[i] * x[i];
    out[f] = Math.sqrt(s / FRAME);
  }
  return out;
}

function correlation(a, b) {
  const n = Math.min(a.length, b.length);
  let ma = 0;
  let mb = 0;
  for (let i = 0; i < n; i++) {
    ma += a[i];
    mb += b[i];
  }
  ma /= n;
  mb /= n;
  let num = 0;
  let da = 0;
  let db = 0;
  for (let i = 0; i < n; i++) {
    const u = a[i] - ma;
    const v = b[i] - mb;
    num += u * v;
    da += u * u;
    db += v * v;
  }
  return num / Math.sqrt(da * db);
}

function rmsDb(x) {
  let s = 0;
  for (let i = 0; i < x.length; i++) s += x[i] * x[i];
  return 20 * Math.log10(Math.max(Math.sqrt(s / x.length), 1e-12));
}

benchTest(
  'THE CHUNKING PIN (real model): a 70 s input matches an unchunked run — bit-exact before the first seam, envelope-equivalent throughout, no seam dip — with peak RSS bounded below the unchunked run',
  () => {
    requireModels();

    const source = prepareSource();
    // The fixture must actually force chunking, or nothing below means
    // anything. 70 s at 22050 Hz = 1,543,500 samples -> 3 chunks, 2 seams.
    expect(source.length).toBe(70 * VC_SAMPLE_RATE);
    expect(source.length).toBeGreaterThan(SEGMENT_SAMPLES);
    const plan = planVoiceSegments(source.length);
    expect(plan).toHaveLength(3);
    const seams = [crossfadeStart(plan, 0), crossfadeStart(plan, 1)];

    // The reference clip: the fixture's own first 8 s. This test does not
    // measure identity movement (the spike settled that against five real
    // target voices with an INDEPENDENT speaker-verification encoder); it
    // needs only a valid, non-degenerate 256-d target embedding, and using a
    // slice of the source keeps the input preparation resampler-free. The
    // embedding is asserted non-degenerate below.
    const referencePath = writeF32('voice-bench-reference.f32', source.subarray(0, 8 * VC_SAMPLE_RATE));
    const sourcePath = writeF32('voice-bench-source.f32', source);

    const host = runDriver('host', sourcePath, referencePath, 'host');
    const direct = runDriver('direct', sourcePath, referencePath, 'direct');
    console.log(`voiceIntegration host:   ${JSON.stringify(host.verdict)}`);
    console.log(`voiceIntegration direct: ${JSON.stringify(direct.verdict)}`);

    // --- the runs are real and well-formed ---------------------------------
    expect(host.verdict.chunkCount).toBe(plan.length);
    expect(direct.verdict.chunkCount).toBe(plan.length); // what the host WOULD use
    expect(host.verdict.embedVectorLength).toBe(256);
    expect(host.verdict.embedVectorFinite).toBe(true);
    expect(host.verdict.sanitisedSamples).toBe(0);
    expect(direct.verdict.sanitisedSamples).toBe(0);
    for (const r of [host, direct]) {
      expect(r.audio.length).toBe(source.length);
      expect(r.verdict.allFinite).toBe(true);
      expect(r.verdict.rmsDb).toBeGreaterThan(-60); // not silence
      expect(r.verdict.peakAbs).toBeLessThanOrEqual(1.5);
    }
    // It converted rather than passed through: the output is not the input.
    expect(correlation(rmsFrames(host.audio), rmsFrames(source))).toBeLessThan(0.999);

    // --- tolerance 1: PREFIX is bit-identical ------------------------------
    // Everything chunk 0 owns exclusively, minus the discard margin at its
    // far end (chunk 0's own missing right-context, measured to begin 26,265
    // samples before its end — the margin is 16,384, so this stops well
    // inside the clean region).
    const prefixEnd = seams[0] - EDGE_DISCARD_SAMPLES;
    let prefixWorst = 0;
    let firstDiff = -1;
    for (let t = 0; t < prefixEnd; t++) {
      const d = Math.abs(host.audio[t] - direct.audio[t]);
      if (d > 0 && firstDiff < 0) firstDiff = t;
      prefixWorst = Math.max(prefixWorst, d);
    }
    console.log(
      `voiceIntegration: prefix [0, ${prefixEnd}) = ${(prefixEnd / VC_SAMPLE_RATE).toFixed(1)} s, ` +
        `max |host - direct| = ${prefixWorst}, first differing sample ${firstDiff}`
    );
    expect(prefixEnd).toBeGreaterThan(28 * VC_SAMPLE_RATE); // ~28.5 s exact
    expect(prefixWorst).toBe(0);

    // (b) THE MARGIN ASSERTION. Right up to the crossfade — including the
    // stretch where chunk 0 has already begun to drift — the deviation must
    // still be negligible. This is what sizes EDGE_DISCARD, and it is the
    // assertion that fails if the margin is cut back to the spectrogram's own
    // 2 frames: measured 2.05e-7 at 64 frames against 3.37e-1 at 2 frames.
    let toSeamWorst = 0;
    for (let t = 0; t < seams[0]; t++) {
      toSeamWorst = Math.max(toSeamWorst, Math.abs(host.audio[t] - direct.audio[t]));
    }
    console.log(
      `voiceIntegration: up to the crossfade at ${seams[0]}, max |host - direct| = ${toSeamWorst.toExponential(3)} ` +
        `(2-frame margin measures 3.37e-1 here)`
    );
    expect(toSeamWorst).toBeLessThan(1e-4);
    expect(EDGE_DISCARD_SAMPLES).toBe(16384);
    expect(plan[0].end - seams[0]).toBeGreaterThanOrEqual(EDGE_DISCARD_SAMPLES);
    expect(seams[0] - plan[1].start).toBeGreaterThanOrEqual(EDGE_DISCARD_SAMPLES);

    // --- tolerance 2: ENVELOPE equivalence over the whole file -------------
    const hostFrames = rmsFrames(host.audio);
    const directFrames = rmsFrames(direct.audio);
    const envCorr = correlation(hostFrames, directFrames);
    const dbGap = Math.abs(rmsDb(host.audio) - rmsDb(direct.audio));
    console.log(
      `voiceIntegration: envelope correlation ${envCorr.toFixed(4)}, total RMS gap ${dbGap.toFixed(3)} dB`
    );
    // 0.95, not 0.85: every arrangement measured 0.975-0.978, so 0.85 was
    // three times looser than the spread it was bounding. It is still only a
    // coarse same-audio check — see the header, it does not move when the
    // seam breaks.
    expect(envCorr).toBeGreaterThanOrEqual(0.95);
    expect(dbGap).toBeLessThanOrEqual(1.0);

    // --- tolerance 3: SEAM CONTINUITY -------------------------------------
    // LOCAL only — the crossfade window's own RMS against the equal-length
    // windows immediately either side of it. It never looks at the unchunked
    // run, which is the point: that comparison was tried and measured a
    // +/-14.26 dB spread AWAY from any seam, purely from the decoder's
    // rendition-to-rendition decorrelation, so it could not see a seam at all.
    // (The -1.46 dB this file once reported was such a frame, 5,574 samples
    // from the nearest crossfade.)
    const rmsOver = (x, from, to) => {
      let s = 0;
      for (let i = from; i < to; i++) s += x[i] * x[i];
      return Math.sqrt(s / (to - from));
    };
    let worstSeamDb = 0;
    let worstSeamAt = -1;
    let judged = 0;
    for (const s of seams) {
      const inSeam = rmsOver(host.audio, s, s + CROSSFADE_SAMPLES);
      const before = rmsOver(host.audio, s - CROSSFADE_SAMPLES, s);
      const after = rmsOver(host.audio, s + CROSSFADE_SAMPLES, s + 2 * CROSSFADE_SAMPLES);
      const local = (before + after) / 2;
      if (!(local > 1e-5)) continue;
      judged++;
      const db = 20 * Math.log10(Math.max(inSeam, 1e-12) / local);
      if (Math.abs(db) > Math.abs(worstSeamDb)) {
        worstSeamDb = db;
        worstSeamAt = s;
      }
    }
    console.log(
      `voiceIntegration: ${judged} seam(s) judged, worst crossfade-vs-neighbours level change ` +
        `${worstSeamDb >= 0 ? '+' : ''}${worstSeamDb.toFixed(2)} dB (at sample ${worstSeamAt})`
    );
    expect(judged).toBe(seams.length);
    // Measured +2.08 dB. The bound catches a join that drops the signal
    // (-inf) or double-adds it (+4.6 dB at the correlation measured here). It
    // does NOT separate constant power from equal gain at 25 ms — equal gain
    // measures -0.87 dB on this fixture, which is not a defect — so no such
    // claim is made for it.
    expect(Math.abs(worstSeamDb)).toBeLessThan(3.5);

    // --- RSS is bounded ----------------------------------------------------
    // The unchunked path's own measured law is linear in length (~183 MB +
    // 5.4 MB/s), which is the whole reason chunking exists. The chunked run
    // must therefore peak BELOW it on the same input.
    console.log(
      `voiceIntegration: peak RSS host ${host.verdict.peakRssMb} MB vs direct ${direct.verdict.peakRssMb} MB ` +
        `(elapsed ${host.verdict.elapsedMs} ms vs ${direct.verdict.elapsedMs} ms)`
    );
    expect(host.verdict.peakRssMb).toBeGreaterThan(0);
    expect(host.verdict.peakRssMb).toBeLessThan(direct.verdict.peakRssMb);

    // And it does not grow with length the way the unchunked path does:
    // DOUBLE the input and the chunked peak must stay within 25% — the plan
    // gains chunks, not per-run memory. (Only the host is re-run; the
    // unchunked path's growth is its measured law, not something to spend
    // another 140 s of inference re-demonstrating.)
    const doubled = new Float32Array(source.length * 2);
    doubled.set(source, 0);
    doubled.set(source, source.length);
    const doubledPath = writeF32('voice-bench-source-2x.f32', doubled);
    const host2x = runDriver('host', doubledPath, referencePath, 'host2x');
    console.log(`voiceIntegration host 2x: ${JSON.stringify(host2x.verdict)}`);
    expect(host2x.verdict.chunkCount).toBe(planVoiceSegments(doubled.length).length);
    expect(host2x.verdict.chunkCount).toBeGreaterThan(host.verdict.chunkCount);
    expect(host2x.verdict.peakRssMb).toBeLessThan(host.verdict.peakRssMb * 1.25);
  }
);
